declare module "*.module.css";
declare module '*.png';
declare module '*.jpeg';
declare module '*.jpg';
declare module '*.svg';
declare module '*.webp';
declare module "react-transition-group";
declare module "@fortawesome/react-fontawesome";
declare module "@fortawesome/free-solid-svg-icons";
